on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test workflow
        uses: ./
        with:
          labels: | 
            ci-ready
#          repo: Gymondo-git/ios-app
#          number: 2021
#          base_branch: develop
#        run: |
#          echo "hello"
#        uses: andrelouw/action-add-label@v0.1